export type AssetVariant = "image" | "video" | "svg";

export type AssetDefinition = {
  id: string;
  label: string;
  path: string | null;
  aspectRatio: string;
  variant: AssetVariant;
  alt?: string;
  dimensions?: string;
};

export const ASSETS: Record<string, AssetDefinition> = {
  "brand-logo-primary": {
    id: "brand-logo-primary",
    label: "Frugel logo (red) — for light backgrounds",
    path: "/user_logo/furgel-logo-red-version.png",
    aspectRatio: "240/64",
    variant: "image",
    alt: "Frugel — Taste Meets Soul",
  },
  "brand-logo-light": {
    id: "brand-logo-light",
    label: "Frugel logo (white) — for dark backgrounds",
    path: "/user_logo/furgel-logo-white-version.png",
    aspectRatio: "240/64",
    variant: "image",
    alt: "Frugel — Taste Meets Soul",
  },
  "hero-product-arrangement": {
    id: "hero-product-arrangement",
    label: "Hero product still-life arrangement",
    path: null,
    aspectRatio: "16/9",
    variant: "image",
    dimensions: "1920×1080 · 8–10 products from all 6 categories",
    alt: "Frugel product range artistic arrangement",
  },
  "hero-drip-svg": {
    id: "hero-drip-svg",
    label: "Logo drip animation SVG path",
    path: null,
    aspectRatio: "1/1",
    variant: "svg",
    dimensions: "Animated red drip path",
  },
  "category-glaze-gel": {
    id: "category-glaze-gel",
    label: "Glaze Gel hero shot",
    path: null,
    aspectRatio: "4/5",
    variant: "image",
    dimensions: "600×750 · slow pour over dark cake",
  },
  "category-fruit-filling": {
    id: "category-fruit-filling",
    label: "Fruit Filling hero shot",
    path: null,
    aspectRatio: "4/5",
    variant: "image",
    dimensions: "600×750 · spoon lifting thick scoop",
  },
  "category-crushes-syrups": {
    id: "category-crushes-syrups",
    label: "Crushes & Syrups hero shot",
    path: null,
    aspectRatio: "4/5",
    variant: "image",
    dimensions: "600×750 · bottle tilted, liquid splash",
  },
  "category-sugar-fondant": {
    id: "category-sugar-fondant",
    label: "Sugar Fondant hero shot",
    path: null,
    aspectRatio: "4/5",
    variant: "image",
    dimensions: "600×750 · hands shaping fondant",
  },
  "category-fruit-jam": {
    id: "category-fruit-jam",
    label: "Fruit Jam hero shot",
    path: null,
    aspectRatio: "4/5",
    variant: "image",
    dimensions: "600×750 · spreading on warm bread",
  },
  "category-chocolate-sauce": {
    id: "category-chocolate-sauce",
    label: "Chocolate Sauce hero shot",
    path: null,
    aspectRatio: "4/5",
    variant: "image",
    dimensions: "600×750 · dramatic drizzle on brownie",
  },
  "origin-goa-map": {
    id: "origin-goa-map",
    label: "Illustrated Goa map",
    path: null,
    aspectRatio: "4/3",
    variant: "svg",
    dimensions: "800×600 · hand-drawn style with markers",
  },
  "origin-farm-panel": {
    id: "origin-farm-panel",
    label: "Goa farm / nature panel",
    path: null,
    aspectRatio: "3/4",
    variant: "image",
    dimensions: "1200×1600",
    alt: "Goa cashew farm landscape",
  },
  "origin-factory-panel": {
    id: "origin-factory-panel",
    label: "Kundaim IDC factory / lab panel",
    path: null,
    aspectRatio: "3/4",
    variant: "image",
    dimensions: "1200×1600",
    alt: "Frugel production facility at Kundaim IDC",
  },
  "problem-fruit-mango": {
    id: "problem-fruit-mango",
    label: "Mango silhouette SVG",
    path: null,
    aspectRatio: "1/1",
    variant: "svg",
    dimensions: "80×80",
  },
  "problem-fruit-cashew": {
    id: "problem-fruit-cashew",
    label: "Cashew silhouette SVG",
    path: null,
    aspectRatio: "1/1",
    variant: "svg",
    dimensions: "80×80",
  },
  "problem-fruit-kokum": {
    id: "problem-fruit-kokum",
    label: "Kokum silhouette SVG",
    path: null,
    aspectRatio: "1/1",
    variant: "svg",
    dimensions: "80×80",
  },
  "innovation-wfc-bottle": {
    id: "innovation-wfc-bottle",
    label: "1 Ltr Whole Fruit Crush bottle — backlit hero",
    path: null,
    aspectRatio: "3/4",
    variant: "image",
    dimensions: "800×1067 · fruit chunks visible, spotlight",
    alt: "Frugel 1 Ltr Whole Fruit Crush with visible fruit chunks",
  },
  "founders-farm-panel": {
    id: "founders-farm-panel",
    label: "Farm / Goa world panel",
    path: null,
    aspectRatio: "3/4",
    variant: "image",
    dimensions: "1200×1600",
    alt: "Goa orchard landscape",
  },
  "founders-lab-panel": {
    id: "founders-lab-panel",
    label: "Lab / kitchen world panel",
    path: null,
    aspectRatio: "3/4",
    variant: "image",
    dimensions: "1200×1600",
    alt: "Professional food lab",
  },
  "founders-couple-photo": {
    id: "founders-couple-photo",
    label: "Founders portrait",
    path: null,
    aspectRatio: "4/5",
    variant: "image",
    dimensions: "800×1000",
    alt: "Frugel founders",
  },
  "dealer-india-map": {
    id: "dealer-india-map",
    label: "Simplified India SVG map",
    path: null,
    aspectRatio: "8/9",
    variant: "svg",
    dimensions: "800×900 · stroke-animatable",
  },
  "enquiry-orchard-bg": {
    id: "enquiry-orchard-bg",
    label: "Cashew orchard parallax background",
    path: null,
    aspectRatio: "16/9",
    variant: "image",
    dimensions: "1920×1080",
    alt: "Cashew orchard background",
  },
  "enquiry-orchard-bg-mobile": {
    id: "enquiry-orchard-bg-mobile",
    label: "Enquiry mobile background",
    path: null,
    aspectRatio: "3/4",
    variant: "image",
    dimensions: "768×1024",
    alt: "Cashew orchard background",
  },
  "footer-drip-backdrop": {
    id: "footer-drip-backdrop",
    label: "Oversized drip motif backdrop",
    path: null,
    aspectRatio: "2/1",
    variant: "svg",
    dimensions: "Decorative · low opacity red",
  },
};

export function getAsset(id: string): AssetDefinition | undefined {
  return ASSETS[id];
}
